name: metaT_pipe
channels:
  - conda-forge
  - bioconda
dependencies:
  - drep
  - cd-hit
  - python=3.*
  - pandas
  - pytest
  - scikit-bio
  - prodigal
  - mmseqs2!=10.6d92c
  - hmmer!=3.3.1
  - trnascan-se >=2
  - sqlalchemy
  - barrnap
  - altair >=4
  - openpyxl
  - networkx
  - ruby
  - parallel
  - dram
  - argparse
  - numpy
  - matplotlib
  - pysam
  - hmmer
  - prodigal
  - pplacer
  - gtdbtk
  - coverm
  - ruby
  - samtools
  - bedtools >2.24
  - pip
  - pip:
    - DRAM-bio
    - checkm-genome
